order: 1
title: Default
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: content
        field:
          type: markdown
          localizable: true
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          required: true
          localizable: true
          validate:
            - required
      -
        handle: date
        field:
          type: date
          required: true
          validate:
            - required
      -
        handle: tags
        field:
          type: terms
          taxonomies:
            - type
          display: 'Project Type'
          mode: select
          listable: hidden
      -
        handle: type
        field:
          type: terms
          taxonomies:
            - type
          display: 'Project Type'
          mode: select
