title: Project
sections:
  main:
    display: Details
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          width: 66
          localizable: true
          validate:
            - required
      -
        handle: slug
        field:
          type: text
          required: true
          localizable: true
          width: 33
          validate:
            - required
      -
        handle: location
        field:
          type: text
          width: 66
          localizable: true
      -
        handle: publish_date
        field:
          type: date
          display: 'Publish Date'
          allow_blank: false
          allow_time: false
          earliest_date: 'January 1, 2018'
      -
        handle: type
        field:
          type: terms
          taxonomies:
            - type
          display: 'Project Type'
          mode: select
          width: 50
          validate: required
      -
        handle: description
        field:
          type: bard
          display: Description
          save_html: true
          buttons:
            - bold
            - italic
            - unorderedlist
            - orderedlist
            - html
            - quote
            - codeblock
            - h1
            - h2
            - h3
            - h4
            - h5
            - h6
            - anchor
  images:
    display: Images
    fields:
      -
        handle: images
        field:
          type: assets
          display: Images
          container: assets
          folder: projects
          listable: hidden
          mode: grid
          restrict: false
          allow_uploads: true
