title: Project
sections:
  main:
    display: Details
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          width: 66
          localizable: true
          validate:
            - required
      -
        handle: slug
        field:
          type: text
          required: true
          localizable: true
          width: 33
          validate:
            - required
      -
        handle: location
        field:
          type: text
          width: 66
          localizable: true
      -
        handle: description
        field:
          type: bard
          display: Description
          save_html: true
          buttons:
            - bold
            - italic
          listable: hidden
          always_show_set_button: false
          toolbar_mode: fixed
          link_noopener: false
          link_noreferrer: false
          target_blank: false
          reading_time: false
          fullscreen: true
          allow_source: true
          enable_input_rules: true
          enable_paste_rules: true
      -
        handle: photographer
        field:
          input_type: text
          antlers: false
          display: Photographer
          type: text
          icon: text
          listable: hidden
      -
        handle: photographer_website
        field:
          input_type: text
          antlers: false
          display: 'Photographer Website'
          type: text
          icon: text
          listable: hidden
          validate:
            - active_url
  images:
    display: Images
    fields:
      -
        handle: lead_image
        field:
          mode: grid
          container: assets
          restrict: false
          allow_uploads: true
          max_files: 1
          display: 'Lead Image'
          type: assets
          icon: assets
          listable: hidden
      -
        handle: images
        field:
          type: assets
          display: Images
          container: assets
          folder: projects
          listable: hidden
          mode: grid
          restrict: true
          allow_uploads: true
  style:
    display: Style
    fields:
      -
        import: full_screen_style
        prefix: project_
  sidebar:
    display: Sidebar
    fields:
      -
        handle: date
        field:
          type: date
          required: true
          validate:
            - required
      -
        handle: project_type
        field:
          type: terms
          taxonomies:
            - project_type
          display: 'Project Type'
          mode: select
          listable: hidden
      -
        handle: in_progress
        field:
          display: 'In progress'
          type: toggle
          icon: toggle
          listable: hidden
