title: Project
sections:
  main:
    display: Details
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          width: 66
          localizable: true
          validate:
            - required
      -
        handle: slug
        field:
          type: text
          required: true
          localizable: true
          width: 33
          validate:
            - required
      -
        handle: location
        field:
          type: text
          width: 66
          localizable: true
      -
        handle: type
        field:
          type: terms
          taxonomies:
            - type
          display: 'Project Type'
          mode: select
          width: 50
          validate: required
      -
        handle: description
        field:
          type: bard
          display: Description
          save_html: true
          buttons:
            - bold
            - italic
            - unorderedlist
            - orderedlist
            - html
            - quote
            - codeblock
            - h1
            - h2
            - h3
            - h4
            - h5
            - h6
            - anchor
      -
        handle: photographer
        field:
          input_type: text
          antlers: false
          display: Photographer
          type: text
          icon: text
          listable: hidden
      -
        handle: photographer_website
        field:
          input_type: text
          antlers: false
          display: 'Photographer Website'
          type: text
          icon: text
          listable: hidden
          validate:
            - active_url
  images:
    display: Images
    fields:
      -
        handle: images
        field:
          type: assets
          display: Images
          container: assets
          folder: projects
          listable: hidden
          mode: grid
          restrict: true
          allow_uploads: true
  style:
    display: Style
    fields:
      -
        import: full_screen_style
        prefix: project_
  sidebar:
    display: Sidebar
    fields:
      -
        handle: date
        field:
          type: date
          required: true
          validate:
            - required
