title: Project
sections:
  main:
    display: Details
    fields:
      title:
        type: text
        width: 66
        localizable: true
      slug:
        type: text
        width: 33
      location:
        type: text
        width: 66
        localizable: true
      publish_date:
        display: Publish Date
        type: date
        allow_blank: false
        allow_time: false
        earliest_date: January 1, 2018
      type:
        type: taxonomy
        display: Project Type
        taxonomy: type
        width: 50
        validate: required
      description:
        type: redactor
        display: Description
  images:
    display: Images
    fields:
      images:
        type: assets
        display: Images
        container: main
        folder: projects
