title: Project
sections:
  main:
    display: Details
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          width: 66
          localizable: true
          validate:
            - required
      -
        handle: slug
        field:
          type: text
          required: true
          localizable: true
          width: 33
          validate:
            - required
      -
        handle: location
        field:
          type: text
          width: 66
          localizable: true
      -
        handle: type
        field:
          type: terms
          display: 'Project Type'
          width: 50
          validate: required
          taxonomies:
            - type
      -
        handle: description
        field:
          type: bard
          display: Description
          save_html: true
          buttons:
            - bold
            - italic
            - unorderedlist
            - orderedlist
            - html
            - quote
            - codeblock
            - h1
            - h2
            - h3
            - h4
            - h5
            - h6
            - anchor
  images:
    display: Images
    fields:
      -
        handle: images
        field:
          type: assets
          display: Images
          container: main
          folder: projects
  sidebar:
    display: Sidebar
    fields:
      -
        handle: date
        field:
          type: date
          required: true
          validate:
            - required
      -
        handle: parent
        field:
          type: entries
          collections:
            - pages
          max_items: 1
          listable: false
          localizable: true
